using FutureEducationalPlatform.Application.DTOS.StudentQuestionAnswerDtos;
using MediatR;
public record CreateStudentQuestionAnswerRequest(CreateStudentQuestionAnswerDto CreateStudentQuestionAnswerDto):IRequest<string>;
