using FutureEducationalPlatform.Application.DTOS.ComprehensiveExamDtos;
using MediatR;
public record CreateComprehensiveExamRequest(CreateComprehensiveExamDto CreateComprehensiveExamDto):IRequest<string>;
